### ISSUE TITLE
Agilent file sequential scan conversion

### ISSUE THREAD

**Issue by warkdave** [Wang-Bioinformatics-Lab/GNPS2_Workflows#10]
This function was in https://gnps-quickstart.ucsd.edu/conversion. It's essential for making our Agilent QTOF MS/MS files usable in Library search workflows.

**Comment by mwang87** [comment]
Thanks Dave, we'll have to refactor it and deploy it on the GNPS2 infrasturcture. I think likely v1 we'll include only conversion and none of the other quickstart features.

**Comment by mwang87** [comment]
Give this a try!

https://quickstart.gnps2.org/conversion

**Comment by warkdave** [comment]
![image](https://github.com/Wang-Bioinformatics-Lab/GNPS2_Workflows/assets/142350355/99b69171-d822-4871-950c-83c2ef986154)

**Comment by mwang87** [comment]
Can you describe the problem and what you tried to do and share the input
data?

Ming

**Comment by warkdave** [comment]
What I did:
1. Dragged a file (75MB MZXML) into the window, it completed uploading indicated by the "checkmark" popup.
2. Clicked Convert Uploaded Agilent Files. Converting Please Wait popup appears with spinning circle.
3. Nothing else happened. I waited about 5 minutes and opened the console to see if there was any indication of HTTP response or error code.

Here is the data file: https://drive.google.com/file/d/1PF91IJ_pbVvB8qoPjOOtpYu4vxi20xNs/view?usp=drive_link
It's an Agilent .d file, QTOF ESI- MS2, that was converted using MSConvert through the process that was in the GNPS documentation.

**Comment by mwang87** [comment]
Verified and fixed.
