### ISSUE TITLE
[FBMN] Link to Boxplot

### ISSUE THREAD

**Issue by joyjin1** [Wang-Bioinformatics-Lab/GNPS2_Workflows#41]
Could we have a link to plot the boxplot for each feature, using the metadata and feature quant table in FBMN? Right now we are mannually generating boxplots on https://plotter.gnps2.org/, but it only supports GNPS1 USI link.

**Comment by mwang87** [comment]
Done: 

https://plotter.gnps2.org/?gnps_quant_table_usi=mzspec:GNPS2:TASK-b5e4761dd69e40e086199df848e18de7-nf_output/clustering/featuretable_reformated.csv&gnps_metadata_table_usi=mzspec:GNPS2:TASK-b5e4761dd69e40e086199df848e18de7-nf_output/metadata/merged_metadata.tsv&feature=27714
