### ISSUE TITLE
FBMN workflow: no metadata output in graphML node table

### ISSUE THREAD

**Issue by idswillemsen** [Wang-Bioinformatics-Lab/GNPS2_Workflows#51]
Hi all,

When running the FBMN workflow with metadata, the attribute output is not present in the output .graphML file. I'd be interested in having the summed peak intensity for my treatments so I can visualize them. 

Link to the FBMN job: https://gnps2.org/status?task=52dabc47aa614b1caad69e4cc4429b3a.

When running the FBMN task in GNPS1 I am able to get the outputs for the groups so something seems to be going wrong.

Thank you!

**Comment by mwang87** [comment]
The feature table is not formatted correctly. There is no trailing Peak area on the columns for the quants.
