### ISSUE TITLE
Classic Molecular Networking workflow not working with Bruker converted mzml files

### ISSUE THREAD

**Issue by Giovanni911** [Wang-Bioinformatics-Lab/GNPS2_Workflows#52]
I tried to run a Classic Molecular Networking workflow by using a mzml file obtained by converting Bruker raw files with their in-house algorithm (using mass convert seems to not be an option since it produces a discrepancy between MS1 and MS2). However when I run these mzml files in GNPS2 it fails, and I get the following report:

Workflow execution completed unsuccessfully!
The exit status of the task that caused the workflow execution to fail was: 1.

The full error message was:

Error executing process > 'mscluster (1)'

Caused by:
  Process `mscluster (1)` terminated with an error exit status (1)

Command executed:

  mkdir clustering
  python /app/workflows_user/classical_networking_workflow/bin/scripts/mscluster_wrapper.py     input_spectra /app/workflows_user/classical_networking_workflow/bin/binaries     spectra     clustering     --min_cluster_size 2     --pm_tolerance 0.02     --fragment_tolerance 0.02     --min_peak_intensity 0.0

Command exit status:
  1

Command output:
  no pyteomics

Command error:
  DEBUG: main_specnets.cpp : 670: execMode = sps
  DEBUG: main_specnets.cpp : 671: GenoMS_FLAG=X
  DEBUG: main_specnets.cpp : 672: Merge_FLAG=X
  DEBUG: main_specnets.cpp : 674
  DEBUG: main_specnets.cpp : 676: SH1:179b02ee5e6f1f067be7c3a7f51a809125d64014
  DEBUG: main_specnets.cpp : 711: initialStageString = 
  DEBUG: main_specnets.cpp : 717: finalStageString = mscluster
  DEBUG: main_specnets.cpp : 719: commandLineParams.getValue("SINGLE_STEP") = 
  DEBUG: main_specnets.cpp : 727: ip.getValue("GRID_PARAMS", "XXX") = XXX
  DEBUG: main_specnets.cpp : 124: p.getValue("GRID_PARAMS", "XXX") = XXX
  DEBUG: main_specnets.cpp : 781: initialStageString = 
  DEBUG: main_specnets.cpp : 786: initialStageString = begin
  DEBUG: main_specnets.cpp : 792: finalStageString = mscluster
  DEBUG: main_specnets.cpp : 797: finalStageString = mscluster
  DEBUG: ../../../trunk/StatusFile.cpp : 31: Updated program status to Running
  DEBUG: main_specnets.cpp : 839: initialStage = 0
  DEBUG: main_specnets.cpp : 841: finalStage = 2
  DEBUG: main_specnets.cpp : 848: resumeFlag = 0
  DEBUG: main_specnets.cpp : 854: gridExecutionFlag = 0
  DEBUG: main_specnets.cpp : 859: Spectral Networks 2.0.0: session started on: Thu May  2 09:18:49 2024
  
  DEBUG: main_specnets.cpp : 860: Starting stage: [begin] on: Thu May  2 09:18:49 2024
  
  DEBUG: main_specnets.cpp : 417: Made directory 'spectra'
  DEBUG: main_specnets.cpp : 417: Made directory 'spectra/grid_scoring'
  DEBUG: main_specnets.cpp : 417: Made directory 'aligns'
  DEBUG: main_specnets.cpp : 417: Made directory 'specnets'
  DEBUG: main_specnets.cpp : 417: Made directory 'homology'
  DEBUG: main_specnets.cpp : 417: Made directory 'homology/grid_t'
  DEBUG: main_specnets.cpp : 417: Made directory 'homology/grid_d'
  DEBUG: main_specnets.cpp : 417: Made directory 'homology/grid2_t'
  DEBUG: main_specnets.cpp : 417: Made directory 'homology/grid2_d'
  DEBUG: main_specnets.cpp : 417: Made directory 'report'
  DEBUG: main_specnets.cpp : 417: Made directory 'ReportData'
  DEBUG: main_specnets.cpp : 417: Made directory 'assembly'
  DEBUG: main_specnets.cpp : 927: No amino acid masses loaded. Using defaults
  DEBUG: main_specnets.cpp : 939
  DEBUG: main_specnets.cpp : 153
  DEBUG: main_specnets.cpp : 182
  ERROR: main_specnets.cpp : 262: Input spectra set is empty
  ERROR: main_specnets.cpp : 263: Please make sure input files are 32-bit uncompressed mzXML files that contain MS/MS spectra
  ERROR: main_specnets.cpp : 949: Failed loading initial data.
  DEBUG: ../../../trunk/StatusFile.cpp : 31: Updated program status to Error

Work dir:
  /data/nf_data/server/nf_work/d42c12e601a444e188a77cf18fbcad86/c0/25d341221118268a40db44a4a90068

Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

**Comment by mwang87** [comment]
I would recommend using timsconvert 

https://academic.oup.com/bioinformatics/article/38/16/4046/6618521

**Comment by Giovanni911** [comment]
I will try thanks!
